#!/usr/bin/env sh

set -e
set -x

clang -Ofast -Wall -Wextra -Werror -pedantic -std=c99 -arch arm64 -arch x86_64 term-size.c -o term-size

# $CODE_SIGN_IDENTITY should be the signing identity whose key is available in
# the keychain. For example, `Node.js Foundation`.
if [[ -n $CODE_SIGN_IDENTITY ]]; then
	echo "No CODE_SIGN_IDENTITY environment variable, skipping codesigning" >&2
else
	codesign \
		--sign "$CODE_SIGN_IDENTITY" \
		--options runtime \
		--timestamp \
		term-size
fi
